apiVersion: apps/v1
kind: Deployment
metadata: 
  name: client-deploy
  labels:
    app: client-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-api
  template:
    metadata:
      labels:
        app: client-api
    spec:
      containers:
      - name: client-api-container
        image: nginx
        ports:
        - containerPort: 80
