apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: library-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      containers:
      - name: library-api-container
        image: node
        ports:
        - containerPort: 5000
        
