apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: library-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-api
  template:
    metadata:
      labels:
        app: library-api
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: library-api-container
        image: 192.168.126.128:8083/repository/docker-repo/mern_docker_demo_library-api
        ports:
        - containerPort: 5000
        
