apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: mongo-db
        image: 192.168.126.128:8083/repository/docker-repo/mongo
        ports:
        - containerPort: 27017
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret # Replace with your secret name
                key: MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-db-secret # Replace with your secret name
                key: MONGO_ROOT_PASSWORD

