apiVersion: apps/v1
kind: Deployment 
metadata:
  name: mongo-db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
      - name: mongo-db
        image: 192.168.126.128:8083/repository/docker-repo/mongo
        ports:
        - containerPort: 27017
