apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-api
  template:
    metadata:
      labels:
        app: nginx-api
    spec:
      imagePullSecrets:
      - name: docker-cred
      containers:
      - name: nginx-container
        image: 192.168.126.128:8083/repository/docker-repo/mern_docker_demo_nginx
        ports:
        - containerPort: 8080
        